on:
  workflow_dispatch:
  
jobs:
  update_report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out wiki
        uses: actions/checkout@v2
        with:
          repository: 'shug0131/tt_result_scraping.wiki'
          ref: 'master'
          path: 'tt_result_scraping.wiki'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-renv@v2
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true   
      
      - name: Run the script
        run: Rscript -e 'source("get_results.R")'
      - name: Commit  wiki results
        run: |
          cd tt_result_scraping.wiki
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -am 'Wiki updated' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

      - name: Commit results
        run: |
          cd ..
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -am 'Data updated' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
